# Generated by Django 2.0.7 on 2018-08-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180808_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='setor',
            name='empresa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='Função', to='app.Funcao'),
            preserve_default=False,
        ),
    ]
