# Generated by Django 2.0.7 on 2018-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180808_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AddField(
            model_name='funcao',
            name='setor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='Setor', to='app.Setor'),
            preserve_default=False,
        ),
    ]
