# Generated by Django 2.0.7 on 2018-08-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180808_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(verbose_name='Salário'),
        ),
    ]
